<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  ad:
    roles:
      - windows
      - ad
    platform: windows-server-amd64
    box: devopsgroup-io/windows_server-2012r2-standard-amd64-nocm # VBOX ONLY
    hypervisor: <%= hypervisor %>
    vagrant_cpus: 2
    user: vagrant
    communicator: winrm
    is_cygwin: false
  centos7:
    roles:
      - client
      - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
  centos8:
    roles:
      - client
    platform: el-8-x86_64
    box: centos/stream8
    hypervisor: <%= hypervisor %>
CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
  ssh:
    keepalive: true
    keepalive_interval: 10
    host_key:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:host_key].join("\n#{' '*6}- ") %>
    kex:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:kex].join("\n#{' '*6}- ") %>
    encryption:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:encryption].join("\n#{' '*6}- ") %>
    hmac:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:hmac].join("\n#{' '*6}- ") %>
