---
fixtures:
  repositories:
    auditd: "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core:
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub:
      repo: "https://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    compliance_markup: "https://github.com/simp/pupmod-simp-compliance_markup"
    nscd: "https://github.com/simp/pupmod-simp-nscd"
    openldap: "https://github.com/simp/pupmod-simp-openldap"
    pki: "https://github.com/simp/pupmod-simp-pki"
    simpcat: "https://github.com/simp/pupmod-simp-simpcat"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
    # For acceptance testing
    simp: "https://github.com/simp/pupmod-simp-simp"
    tcpwrappers: "https://github.com/simp/pupmod-simp-tcpwrappers"
  symlinks:
    sssd: "#{source_dir}"
