---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh.git
    nsswitch: https://github.com/simp/puppet-nsswitch.git
    pam: https://github.com/simp/pupmod-simp-pam.git
    oddjob: https://github.com/simp/pupmod-simp-oddjob.git
    resolv: https://github.com/simp/pupmod-simp-resolv.git
    simp: https://github.com/simp/pupmod-simp-simp.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    ssh: https://github.com/simp/pupmod-simp-ssh.git
    systemd:
      repo: https://github.com/simp/puppet-systemd.git
      branch: simp-master
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap.git
    simp_ds389: https://github.com/simp/pupmod-simp-simp_ds389.git
    ds389: https://github.com/simp/pupmod-simp-ds389.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
  symlinks:
    sssd: "#{source_dir}"
