---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    pki: https://github.com/simp/pupmod-simp-pki
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib

    # Fixtures for the AD acceptance test
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    nsswitch: https://github.com/simp/puppet-nsswitch
    pam: https://github.com/simp/pupmod-simp-pam
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    resolv: https://github.com/simp/pupmod-simp-resolv
    simp: https://github.com/simp/pupmod-simp-simp
    ssh: https://github.com/simp/pupmod-simp-ssh
  symlinks:
    sssd: "#{source_dir}"
