<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  ldapserver.beaker:
    roles:
      - ldap
      - default
    platform: el-8-x86_64
    box: centos/stream8
    hypervisor: <%= hypervisor %>

  centos8.beaker:
    roles:
      - client
      - sssdv2
    platform: el-8-x86_64
    box: centos/stream8
    hypervisor: <%= hypervisor %>

  centos7.beaker:
    roles:
      - client
      - sssdv1
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
  ssh:
    keepalive: true
    keepalive_interval: 10
    host_key:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:host_key].join("\n#{' '*6}- ") %>
    kex:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:kex].join("\n#{' '*6}- ") %>
    encryption:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:encryption].join("\n#{' '*6}- ") %>
    hmac:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:hmac].join("\n#{' '*6}- ") %>
