require 'spec_helper'

describe 'sssd::domain' do
  context 'supported operating systems' do
    on_supported_os.each do |os, os_facts|
      context "on #{os}" do
        let(:facts) { os_facts }

        let(:title) { 'ldap' }
        let(:params) do
          {
            id_provider: 'ldap',
          }
        end

        it { is_expected.to compile.with_all_deps }
        it { is_expected.to contain_sssd__config__entry("puppet_domain_#{title}").without_content(%r{=\s*$}) }

        context 'with custom_options' do
          let(:params) do
            super().merge(
              access_provider: 'simple',
              custom_options: {
                # Deliberately out of alphabetical order: the entries are
                # sorted by key before they are rendered.
                'simple_deny_users' => 'baduser',
                'simple_allow_groups' => 'linux-admins,linux-users',
              },
            )
          end

          it { is_expected.to compile.with_all_deps }

          # On sssd::domain, custom_options are ADDITIVE: they do not replace
          # the options generated by the other parameters the way the
          # sssd::service::* classes do.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^id_provider = ldap$})
          }

          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^access_provider = simple$})
          }

          # Sorted by key and appended after the parameter-driven lines.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^access_provider = simple$.*^simple_allow_groups = linux-admins,linux-users\nsimple_deny_users = baduser$}m)
          }
        end
      end
    end
  end
end
