require 'spec_helper'

describe 'sssd::domain' do
  context 'supported operating systems' do
    on_supported_os.each do |os, os_facts|
      context "on #{os}" do
        let(:facts) { os_facts }

        let(:title) { 'ldap' }
        let(:params) do
          {
            id_provider: 'ldap',
          }
        end

        it { is_expected.to compile.with_all_deps }
        it { is_expected.to contain_sssd__config__entry("puppet_domain_#{title}").without_content(%r{=\s*$}) }

        context 'with custom_options' do
          let(:params) do
            super().merge(
              custom_options: {
                # Deliberately out of alphabetical order: the entries are
                # sorted by key before they are rendered.
                'dyndns_update' => 'true',
                'ad_site' => 'Default-First-Site-Name',
              },
            )
          end

          it { is_expected.to compile.with_all_deps }

          # On sssd::domain, custom_options are ADDITIVE: they do not replace
          # the options generated by the other parameters the way the
          # sssd::service::* classes do.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^id_provider = ldap$})
          }

          # Sorted by key and appended after the parameter-driven lines.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^id_provider = ldap$.*^ad_site = Default-First-Site-Name\ndyndns_update = true$}m)
          }
        end

        context 'with simple access provider parameters' do
          let(:params) do
            super().merge(
              access_provider: 'simple',
              simple_allow_groups: ['linux-admins', 'linux-users'],
              simple_deny_users: ['baduser'],
              # Explicitly empty: the option must be omitted, never rendered
              # with an empty value.
              simple_allow_users: [],
            )
          end

          it { is_expected.to compile.with_all_deps }

          # Arrays render as the comma-separated lists sssd-simple(5) expects.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^simple_allow_groups = linux-admins,linux-users$})
          }

          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^simple_deny_users = baduser$})
          }

          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .without_content(%r{simple_allow_users})
          }

          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .without_content(%r{simple_deny_groups})
          }

          # Rendered in sssd-simple(5) order (deny_users before allow_groups),
          # after the other parameter-driven lines.
          it {
            is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
              .with_content(%r{^access_provider = simple$.*^simple_deny_users = baduser\nsimple_allow_groups = linux-admins,linux-users$}m)
          }

          context 'combined with custom_options' do
            let(:params) do
              super().merge(
                custom_options: { 'ad_site' => 'Default-First-Site-Name' },
              )
            end

            it { is_expected.to compile.with_all_deps }

            # The parameter-driven simple_* lines come first; custom_options
            # stay appended at the very end.
            it {
              is_expected.to contain_sssd__config__entry("puppet_domain_#{title}")
                .with_content(%r{^simple_allow_groups = linux-admins,linux-users$.*^ad_site = Default-First-Site-Name$}m)
            }
          end
        end
      end
    end
  end
end
